# Generated by Django 4.2.6 on 2023-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(default=' ', max_length=50)),
                ('comp_sector', models.CharField(default=' ', max_length=50)),
                ('comp_desc', models.CharField(default=' ', max_length=200)),
                ('comp_values', models.TextField(default=' ', max_length=200)),
                ('comp_street', models.CharField(default=' ', max_length=50)),
                ('city', models.CharField(default=' ', max_length=50)),
                ('postal_code', models.CharField(default=' ', max_length=10)),
                ('country', models.CharField(default=' ', max_length=50)),
                ('comp_linkedin', models.CharField(default=' ', max_length=100)),
                ('comp_instagram', models.CharField(default=' ', max_length=100)),
            ],
        ),
    ]
