# Generated by Django 4.2.6 on 2023-10-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entryhub_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_stats',
            fields=[
                ('stats_id', models.IntegerField(primary_key=True, serialize=False)),
                ('active_jobs', models.IntegerField(default=0)),
                ('app_received', models.IntegerField(default=0)),
                ('candidates_match', models.IntegerField(default=0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entryhub_company.company')),
            ],
        ),
        migrations.CreateModel(
            name='company_contact',
            fields=[
                ('comp_contactid', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(default=' ', max_length=50)),
                ('contact_role', models.CharField(default=' ', max_length=100)),
                ('contact_emailid', models.CharField(default=' ', max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entryhub_company.company')),
            ],
        ),
    ]
