# Generated by Django 4.2.6 on 2023-10-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entryhub_company', '0002_company_stats_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_desc',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_values',
            field=models.TextField(default=' '),
        ),
    ]
