# Generated by Django 4.2.6 on 2023-10-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0002_table2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table2',
        ),
    ]
