# Generated by Django 4.2.6 on 2023-10-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0004_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
