# Generated by Django 4.2.6 on 2023-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0007_candidate_disability_candidate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='postal_code',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='street',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
