# Generated by Django 4.2.6 on 2023-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0010_candidate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(default=' ', upload_to='\\images'),
        ),
    ]
