# Generated by Django 4.2.6 on 2023-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0011_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='disability',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='marital_status',
            field=models.CharField(default=' ', max_length=25),
        ),
    ]
