# Generated by Django 4.2.6 on 2023-10-21 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0013_remove_candidate_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_sts', models.CharField(default=' ', max_length=50)),
                ('account_hibernate', models.BooleanField(default=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_log.candidate')),
            ],
        ),
    ]
