# Generated by Django 4.2.6 on 2023-10-22 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0015_candidate_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_certification',
            name='expiry_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='candidate_certification',
            name='issuing_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_certification',
            name='credential_url',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate_certification',
            name='org_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
