# Generated by Django 4.2.6 on 2023-10-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0017_alter_candidate_certification_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_exp',
            name='date_of_termination',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Candidate_edu',
            fields=[
                ('edu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('univ', models.CharField(default=' ', max_length=50)),
                ('course', models.CharField(default=' ', max_length=50)),
                ('degree', models.CharField(default=' ', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_log.candidate')),
            ],
        ),
    ]
