# Generated by Django 4.2.6 on 2023-10-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0018_alter_candidate_exp_date_of_termination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_reference',
            fields=[
                ('ref_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ref_name', models.CharField(default=' ', max_length=50)),
                ('ref_Comp', models.CharField(default=' ', max_length=50)),
                ('ref_role', models.CharField(default=' ', max_length=50)),
                ('ref_Date', models.DateField(null=True)),
                ('ref_desc', models.TextField(max_length=100)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_log.candidate')),
            ],
        ),
    ]
