# Generated by Django 4.2.6 on 2023-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0021_candidate_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='photo',
            field=models.ImageField(default=' ', upload_to='\\images'),
        ),
    ]
