# Generated by Django 4.2.6 on 2023-10-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0026_job_job_expiry_date_job_job_sal_expect'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_exp_of_emp',
            field=models.IntegerField(default=0),
        ),
    ]
