# Generated by Django 4.2.6 on 2023-10-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0027_job_job_exp_of_emp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
